In [ ]:
"""
Data Cleaning Concepts to use to resolve this problem.  Use the AB_NYC dataset (CSV file) attached to Week4 folder.



Load the Airbnb dataset into a Pandas DataFrame.
Randomly sample 1,000 rows from the dataset.


Identify missing values in the dataset.
Apply an appropriate cleaning strategy:
Detect outliers in price, minimum_nights
Decide whether to remove, keep outliers


Identify irrelevant or redundant columns.
Remove at least three attributes and justify why.
Show me / Reduce data to only show attributes useful for predicting listing price


Most frequently (ie. 80% of the time) used Python statements for data cleaning purposes are:

df.info()

df.isna().sum()

dropna() / fillna()

SQL filtering

drop_duplicates()



There are many others.  Experiment around with various Python statements that are used for data cleaning.
"""

In [3]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\kesha\Downloads\AB_NYC_2019.csv")

# Display basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [4]:
sample_df = df.sample(n=1000, random_state=42)

print(sample_df.shape)

(1000, 16)

In [5]:
sample_df.isna().sum()

id                                  0
name                                0
host_id                             0
host_name                           0
neighbourhood_group                 0
neighbourhood                       0
latitude                            0
longitude                           0
room_type                           0
price                               0
minimum_nights                      0
number_of_reviews                   0
last_review                       214
reviews_per_month                 214
calculated_host_listings_count      0
availability_365                    0
dtype: int64

In [9]:
sample_df["reviews_per_month"] = sample_df["reviews_per_month"].fillna(0)
sample_df["host_name"] = sample_df["host_name"].fillna("Unknown")
sample_df["name"] = sample_df["name"].fillna("No Name")
print(sample_df["reviews_per_month"])
print(sample_df["host_name"])
print(sample_df["name"])

879      0.71
44383    0.00
15394    0.43
43230    1.88
16332    0.80
         ...
18421    2.52
9146     0.02
36356    0.00
39865    4.21
27627    0.20
Name: reviews_per_month, Length: 1000, dtype: float64
879              Jane
44383       Giancarlo
15394       Alejandro
43230    Sonder (NYC)
16332          Gingie
             ...
18421        Caroline
9146            Keith
36356           Kathy
39865            Tiba
27627          Ashley
Name: host_name, Length: 1000, dtype: object
879                    Come and go as  you please in BKLN!
44383              Spacious, sunny room in Queens/Brooklyn
15394       Private bedroom in high-ceiling 4BR apartment!
43230     Sonder | Stock Exchange | Stunning 3BR + Kitchen
16332                      Spacious 2 Bedroom with Balcony
                               ...
18421                   Modern Apt - 10 min from Manhattan
9146                         15 min walk to Prospect Park!
36356        Nice Couple in A Walk in Basement with Window
39865    Walk toTimes Square,Central Park,Museums, Broa...
27627                       Bright East Village Apartment!
Name: name, Length: 1000, dtype: object

In [10]:
sample_df["last_review"] = sample_df["last_review"].fillna("Not Reviewed")
print(sample_df["last_review"])

879        2019-01-02
44383    Not Reviewed
15394      2017-04-28
43230      2019-06-02
16332      2019-06-03
             ...
18421      2019-06-13
9146       2015-09-17
36356    Not Reviewed
39865      2019-06-23
27627      2018-08-15
Name: last_review, Length: 1000, dtype: object

In [12]:
sample_df.drop_duplicates(inplace=True)
sample_df.duplicated().sum()

np.int64(0)

In [13]:
Q1 = sample_df["minimum_nights"].quantile(0.25)
Q3 = sample_df["minimum_nights"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

night_outliers = sample_df[
    (sample_df["minimum_nights"] < lower) |
    (sample_df["minimum_nights"] > upper)
]

print(len(night_outliers))

141

In [14]:
Q1 = sample_df["price"].quantile(0.25)
Q3 = sample_df["price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

price_outliers = sample_df[
    (sample_df["price"] < lower) |
    (sample_df["price"] > upper)
]

print(len(price_outliers))

46

In [15]:
sample_df.drop("id", axis=1, inplace=True)
sample_df.drop("host_id", axis=1, inplace=True)
sample_df.drop("host_name", axis=1, inplace=True)

In [16]:
print(sample_df.drop)

<bound method DataFrame.drop of                                                     name neighbourhood_group  \
879                  Come and go as  you please in BKLN!            Brooklyn
44383            Spacious, sunny room in Queens/Brooklyn              Queens
15394     Private bedroom in high-ceiling 4BR apartment!           Manhattan
43230   Sonder | Stock Exchange | Stunning 3BR + Kitchen           Manhattan
16332                    Spacious 2 Bedroom with Balcony           Manhattan
...                                                  ...                 ...
18421                 Modern Apt - 10 min from Manhattan              Queens
9146                       15 min walk to Prospect Park!            Brooklyn
36356      Nice Couple in A Walk in Basement with Window            Brooklyn
39865  Walk toTimes Square,Central Park,Museums, Broa...           Manhattan
27627                     Bright East Village Apartment!           Manhattan

                   neighbourhood  latitude  longitude        room_type  price  \
879                   Kensington  40.64354  -73.97777  Entire home/apt     89
44383                  Ridgewood  40.70666  -73.90779     Private room     30
15394             Hell's Kitchen  40.76116  -73.99016     Private room    120
43230         Financial District  40.70763  -74.01050  Entire home/apt    470
16332                East Harlem  40.79658  -73.93287  Entire home/apt    199
...                          ...       ...        ...              ...    ...
18421              East Elmhurst  40.75720  -73.89569  Entire home/apt    100
9146   Prospect-Lefferts Gardens  40.65887  -73.94882     Private room     30
36356               Borough Park  40.63416  -74.00722     Private room     50
39865             Hell's Kitchen  40.76356  -73.98956  Entire home/apt    230
27627               East Village  40.72411  -73.98872  Entire home/apt     99

       minimum_nights  number_of_reviews   last_review  reviews_per_month  \
879                 3                 62    2019-01-02               0.71
44383              21                  0  Not Reviewed               0.00
15394               2                 17    2017-04-28               0.43
43230               2                  5    2019-06-02               1.88
16332               2                 30    2019-06-03               0.80
...               ...                ...           ...                ...
18421               3                 87    2019-06-13               2.52
9146                6                  1    2015-09-17               0.02
36356               2                  0  Not Reviewed               0.00
39865               1                 17    2019-06-23               4.21
27627               5                  4    2018-08-15               0.20

       calculated_host_listings_count  availability_365
879                                 1               189
44383                               1                73
15394                               1                 0
43230                             327               272
16332                               1                30
...                               ...               ...
18421                               1               322
9146                                1                 0
36356                              10               365
39865                               5               282
27627                               1                 0

[1000 rows x 13 columns]>

In [19]:

price_df = sample_df[
    [
        "neighbourhood_group",
        "neighbourhood",
        "latitude",
        "longitude",
        "room_type",
        "minimum_nights",
        "number_of_reviews",
        "reviews_per_month",
        "calculated_host_listings_count",
        "availability_365",
        "price"
    ]
]
price_df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [20]:
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [21]:
df.dropna()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,Lovely Privet Bedroom with Privet Restroom,83554966,Rusaa,Manhattan,Upper East Side,40.78099,-73.95366,Private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,No.2 with queen size bed,257683179,H Ai,Queens,Flushing,40.75104,-73.81459,Private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,Seas The Moment,211644523,Ben,Staten Island,Great Kills,40.54179,-74.14275,Private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1B-1B apartment near by Metro,273841667,Blaine,Bronx,Mott Haven,40.80787,-73.92400,Entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,40.69805,-73.92801,Private room,30,1,1,2019-07-08,1.00,1,1

In [22]:
df.fillna(0)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0,0.00,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,0,0.00,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,0,0.00,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,0,0.00,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,0,0.00,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,0,0.00,1,23

In [23]:
df.drop_duplicates()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23